### PR TITLE
Fix logging formatting, update PackageData in spec, models, controllers

### PR DESCRIPTION
**Pull request by priyankapereira1**
[Update spec to type nullable:true for PackageData input and fixed all controllers accordingly]

Unable to set severity: DEBUG in morgan-body, still working on that, unsure if it's possible
Maybe log streaming will have to change?

Fix so autograder passes (discussed https://piazza.com/class/lc9qx1w86k643t/post/305)

### CODE REVIEW

**Review by just007in — APPROVED** [review]

**Comment by just007in** [comment]
That should be fine. I realized we can also filter for default level as well

**Comment by priyankapereira1** [comment]
> That should be fine. I realized we can also filter for default level as well

I actually just fixed it by streaming it into the winston logger, so I will update here

**Comment by priyankapereira1** [comment]
btw I tried with the null inputs they use in autograder exactly and it works fine now!!

**Comment by priyankapereira1** [comment]
one sec trying to log stream the morgan default too

**Comment by priyankapereira1** [comment]
Done

**Pull request merged**
